### ISSUE TITLE
Webhook room_update not working

### ISSUE THREAD

**Issue by johnsoliman** [eyeson-team/eyeson-php#1]
The php-library doesn't have **room_update** as  a possible Webhook type but **room_instance_update**
-> eyeson-php/src/Resources/Webhook.php:9

Moreover when replacing the webhook room_instance_update with room_update in the list you get an error message, because there is a typo at eyeson-php/src/Resources/Webhook.php:33
The API seems to expect parameter "**types**" not "**type**"! 

I setup the script which gets triggered by the webhook to dump everything what I receive in a logfile in the following order:
`print_r(array(file_get_contents('php://input'), $_POST, $_GET, $_SERVER)`

After someone disconnects from the room the logfile gets created with the following output, which does NOT include  started_at, ended_at and the participants as stated in the documentation at https://eyeson-team.github.io/api/api-reference/#register-webhooks
`{"api_key":"...","type":"room_update","room":{"id":"Testraum","name":"Therapie","ready":true,"shutdown":false,"sip":{"uri":"...","domain":"...","authorizationUser":"..."},"guest_token":"..."}}
`

Is this a bug, is there something still not implemented or am I doing something completely wrong here?

**Comment by unused** [comment]
You can use recent version of the library to register webhooks, the typos have been fixed. The process is totally right, it seems that I've mixed up some other service in the documentation. You receive a webhook with the boolean attribute shutdown, that represents if the meeting has ended. You can simply record this event on your side to get the meeting time.

**Comment by johnsoliman** [comment]
Thanks, but I just discovered that room_update gets only triggered when someone joins a room. After someone disconnects from a room nothing happens automatically. It seems I have to send a request for example another join request, without really joining the room in order to get the desired output with shutdown:true.

Is this intended like this? It would be a lot better if it just automatically triggers on disconnect as well without me having to send periodically a request to check if the room meeting already ended.

**Comment by unused** [comment]
The room update webhook is send whenever the room changes, in case of user disconnects, those users are not removed as participants, therefore you don't receive a new event.

I just checked the shutdown attribute, it works as expected. Did you wait for the two-minute timeout that the meeting is waiting for reconnects until a meeting is closed?

**Comment by johnsoliman** [comment]
Thanks, that's why it worked first time as expected and made me wonder. Still this means we can only estimate a end time. That's not really a clean solution. 

If I understand it right, the event gets triggered when someone joins and when everyone has left the room after a 2 minute timeout. But if someone rejoined the room during the 2 minute delay the end time gets delayed again which makes the overall duration of the room session longer even if there are no 2 active partners in the room.
Moreover we have to subtract 2 minutes from the duration to get the actual session time. 

I know its rare that this could happen but still a possibility. For now I am content with the process. Thanks for your support.

**Comment by unused** [comment]
We always focus on having "clean solutions". Having a timeout is essential, otherwise a session will always cut if a single participant leaves the room by reconnecting or has network issues. We have elaborated a timeout over a long time and many meetings and came to the best result with around two minutes.

You don't have to estimate any meeting, the exact session time is the `timestamp of shutdown - timeout`.
