### ISSUE TITLE
i have an error Class 'VCR\VCR' not found

### ISSUE THREAD

**Issue by vinaysavner** [eyeson-team/eyeson-php#10]
i have an error like "Class 'VCR\VCR' not found" when i am integrate this php code in my codigniter application.
i need help to create it with codeigniter framework.

**Comment by unused** [comment]
We use php-vcr in our testsuite, however this should never be loaded if you load the package properly using composer. Can you provide some details how you did integrate the library into your application?

**Comment by vinaysavner** [comment]
i am using a codigniter framework right now. 
Do you help me to do it in codeigniter.
i am beginner and first i run this command "composer require eyeson/eyeson-php" on cmd 
then for downloading the pakages. this are not running "$ make build $ make test" .

**Comment by vinaysavner** [comment]
even i also download the "https://github.com/eyeson-team/eyeson-php.git" zip and run it. it is showing same error.

**Comment by unused** [comment]
Hi, we've double-checked your issue but could not figure out any problems using the CodeIgniter framework and eyeson-php. We recommend to use composer for any PHP based application. For CodeIgniter you can find the setup instructions in the [official documentation](https://codeigniter4.github.io/userguide/installation/installing_composer.html).
