### ISSUE TITLE
Customize meeting interface

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#14]
Hi, using this PHP package, I can add people to a room and redirect the browser to the room's URL. However, how can I customize the room interface ?

**Comment by unused** [comment]
You can adapt some configuration of the eyeson default GUI like setting a custom logo, disallowing recordings or defining a custom exit-url. Please refer to the [API documentation](https://eyeson-team.github.io/api/api-reference/#eyeson-room) for details.

If you need a custom look & feel or different set of features you can easily build a custom UI. We also provide a [JavaScript package](https://eyeson-team.github.io/js-docs/) that provides tools and helpers.
