### ISSUE TITLE
Customize URL

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#15]
Hi, can we use our own domain in the room's URL ?

**Comment by unused** [comment]
The eyeson web GUI is provided with limited configuration options. We do not provide it for self-hosting. As mentioned in #14 you can create your own user interface, there is also a [quick example](https://github.com/eyeson-team/react-web-gui-example) available.

**Comment by malanciault** [comment]
Thanks. And by building our own interface, would the URL in the participant address bar be eyeson or ours ?

**Comment by unused** [comment]
For sure the URL can be any you like for your own custom GUI as it is self-hosted.
