### ISSUE TITLE
Remove Invite Guest Button

### ISSUE THREAD

**Issue by ugurbakisuzun** [eyeson-team/eyeson-php#16]
Hello Eyeson Team,

Now we completed our platform and trying to implement your API to our backend. But our developer has some problems and questions. So basically, our platform allows trainers to create virtual class and their clients can join class by pay fee on our platform. Therefore :

1 - We want to cancel invite a guest button. Is there any solution for this ?

2 - How can we pretend that guest share its url and invite unpaid other guest. If there is a chance to cancel 'join as a guest' button on "two timer"page, we can do prevent that.

3 - Can we use own domain for event url ? If it is yes how ?

4 - And lastly, you said host can make a layout of participants inside the meeting ? But we couldn't find any feature about that issue in php library ?

Thanks and regards.

**Comment by andrespadron98** [comment]
I have the same questions as you, additionally I would also like to know if you can limit access to some participants since we do not want other unwanted people to enter.

**Comment by unused** [comment]
We do have a room configuration for guest invites on our roadmap and as far as I know it will be released soon, this for sure will include the guest join on the two timer error page. If you need any user management, you can easily do so in your application to allow or restrict a user to join a meeting.

The web interface provided is hosted at eyeson, you can easily build your own user interface on demand. You can find details in the [JavaScript documentation](https://eyeson-team.github.io/js-docs/) as well as in the custom GUI [example](https://github.com/eyeson-team/react-web-gui-example).

Please find information on layout settings in the [API documentatio](https://eyeson-team.github.io/api/api-reference/#layout), I'll try to add corresponding wrapper in the PHP library asap.

**Comment by unused** [comment]
We have updated the [API](https://eyeson-team.github.io/api/api-reference/#eyeson-room), you can use configuration param `options[guest_token_available]` to disallow guest invites.

**Comment by unused** [comment]
We have added layout handling to the package.

```php
$layout = $eyeson->getLayout($room);
$layout->update($userList); // ["5eb3a...994", "5eb3a...d06"]
$layout->useAuto();
$layout->showNames();
$layout->hideNames();
```
