### ISSUE TITLE
Inviting guests

### ISSUE THREAD

**Issue by skillmeeting** [eyeson-team/eyeson-php#17]
Greetings.

I am using your code to launch a meeting. (eyeson->join) Is there a way to check if the call fails so I don't have to invite people before being sure the meeting is going to start? How long do they have before launching their own session?

Thanks

Mike

**Comment by unused** [comment]
Please have a look on the HTTP STATUS of the response to see if your request was successfull. Additionally you won't receive any data on a bad request. You do not have to start anything upfront, simply request a room on demand and forward your user. Do not hesitate to leave a comment if you have any further questions. Best wishes!

**Comment by skillmeeting** [comment]
Thanks for your response.

I have more questions trying to understand the sample code.

I am using "        $room = (array) $eyeson->join($user,$location_id);" to
create a meeting with the meeting's owner as $user. So far, so good.

I can launch the meeting fine with the GUI URL and invite my guests by
email providing the guest link. Great.

How can I control that the people I have invited are really the people
connecting to the meeting as links can be forwarded to third parties?

Also, in the meeting itself where can I show the meeting's name. Seems that
the join gives me back:

[room] => Array (
-------- [id] => SM_1513 string
-------- [name] => Team skillmeeting
and name is my account with you, not any specific name I would provide
somewhere.

Thanks for helping.

Mike

**Comment by unused** [comment]
You can add any number of users to a room, simply use a unique identifier.
Please find a detailed description and further options in the [room section in API documentation](https://eyeson-team.github.io/api/api-reference/#eyeson-room). Any authentication can simply be handled by your application, forward any user afterwards. Best wishes!
