### ISSUE TITLE
API persistent room

### ISSUE THREAD

**Issue by juliengriffonwinwin** [eyeson-team/eyeson-php#19]
Hi,
How to create a "persistent" room with the API "rooms" point ?
Cordialy

**Comment by juliengriffonwinwin** [comment]
I dont understand when the room is automatic destroyed :(

**Comment by unused** [comment]
Hi, you can create and handle any rooms you want in your application. As soon as your user joins the room, send the request to the eyeson API and redirect your user (or show your own custom interface). Therefor you can manage persistent rooms in any way you want in your service and only handle the video call at eyeson. Best wishes!

**Comment by juliengriffonwinwin** [comment]
Hi,

Thanks for your answer !

I understand that at least one user must be in the meeting room otherwise it is destroyed automatically.

The problem is therefore that it is not possible to anticipate the creation of meetings for a big event. 2 or 3 days before for exemple. Event with 20 rooms, 100 participants, viewers, etc. We need to do all at real time witch is very difficult.

Any recommandation ?

Thanks

**Comment by unused** [comment]
No worries, you don't have to prepare anything upfront. Just handle the room/user management on your side (which user belong to which room) and provide your room identifiers when joining a room. Everyone will end up in the correct room and nothing has to be done beforehand.
