### ISSUE TITLE
How to disable buttons

### ISSUE THREAD

**Issue by johnsoliman** [eyeson-team/eyeson-php#2]
I couldn't find something about the matter in the documentation. How to disable some buttons like "recording" using the php-library?

**Update:** Solved this myself. Here is a possible solution which needs to be implemented in the library yet. 
/eyeson-php/src/Eyeson.php:29,36 is missing $options
`  public function join($user, $id=null, $options=array()) {
    if (\is_string($user)) {
      $user = new User(['name' => $user]);
    }
    elseif (\is_array($user)) {
      $user = new User($user);
    }
    return (new Room($this->api, $id))->join($user, $options);
  }`

/eyeson-php/src/Resource/Room.php:24,26 is missing $options
`  public function join(User $user, $options=array()) {
    $params = \array_merge([ "id" => $this->id ],
                           $this->prefix($user->toArray(), 'user'), $this->prefix($options, 'options'));
    $this->data = $this->api->post('/rooms', $params);
    return $this;
  }`

**Comment by unused** [comment]
Hi John, thank you for the hin, I've just update the library and added the missing options for the room.
