### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#21]
Hi, I'm not sure if this is the right place to ask this question as it is not an issue but rather a real question.

we are using the PHP library. I'm seeing that we can add Webhooks. What info will be send to webhooks and when (what tioggers them).

Thanks!

**Comment by unused** [comment]
Thank you for the feedback, I'll update the API documentation and add some example.

**Comment by unused** [comment]
We have update the [webhooks section of the API documentation](https://eyeson-team.github.io/api/api-reference/#register-webhooks). If you have any further questions do not hesitate to leave a message. Best wishes!
