### ISSUE TITLE
aka layers

### ISSUE THREAD

**Issue by juliengriffonwinwin** [eyeson-team/eyeson-php#22]
Hi,

After creating a room and then entering it I try to interact with the interface.

So i try the api point layers like this : (with valid image url)

rooms/kqt19VMlRnhz0g0T1ChDrEe9/layers
with parameters :
{
      +"url": "https://xxxxxxxxx.com/images/aka/bpifrance.png"
      +"z-index": "1"
      +"layout": "auto"
 }

but nothing append.
i just get null in response.

I don't understand how to use the API for sendinf image, video on foreground at real time.

Thanks a lot.
Julien

**Comment by unused** [comment]
Hi Julien, your snippet looks valid, however you might have missed to disable SFU mode when joining the room. No worries, I've prepared an example for you:

```sh
$ curl -X POST \
  -H "Authorization: $(API_KEY)" \
  -d "user[name]=Bob" \
  -d "options[sfu_mode]=disabled" \
  "https://api.eyeson.team/rooms"
$ curl -X POST \
  -d "url=https://eyeson-team.github.io/api/images/eyeson-overlay.png" \
  "https://api.eyeson.team/rooms/$(ACCESS_KEY)/layers"
```

Note: You still won't see the overlay in the default GUI with only one participant as we use the local stream here but on snapshots, broadcasts, recordings, etc. for sure. If filed this as bug in case SFU mode is disabled and we'll update the default GUI so there will be an overlay even with a single participant.

Best wishes!

**Comment by juliengriffonwinwin** [comment]
Hi,
It works fin with a PNG file.
Is it possible to send a MP4 ?
Cordialy

**Comment by unused** [comment]
Hi, we currently do not provide an endpoint to play MP4 files. Best wishes!

**Comment by juliengriffonwinwin** [comment]
Hi,

do you plan this feature ?
The interest is gigantic.

No more need for video management like OBS or other software to add external video during broadcast. Screen sharing for video is very poor.

Waiting for your return

Julien

**Comment by unused** [comment]
Thank you for the comment, I have happily forwarded your request and hope for the best :)

**Comment by juliengriffonwinwin** [comment]
Hi,
Did you plan to develop this feature ? Sending MP4 ?
Thank

**Comment by unused** [comment]
I'll provide you some details via email as soon as possible.
