### ISSUE TITLE
We lost you for a second. Try reloading the page or go

### ISSUE THREAD

**Issue by juliengriffonwinwin** [eyeson-team/eyeson-php#23]
Hi,
When i join a room i sometimes get this error message for no reason with my local network.
I always test in the same place. I got this message this morning from 10:40 am to 10:45 am.
No change source code or something else.
Cordialy

**Comment by unused** [comment]
Thank you for the information, we checked our monitoring and did not see any interruptions. Do you still have any troubles using our services?

**Comment by juliengriffonwinwin** [comment]
No problems today.
The problem appear only 3 days ago
