### ISSUE TITLE
Regarding PHP API

### ISSUE THREAD

**Issue by yogesh-rinologix** [eyeson-team/eyeson-php#25]
Hi Team,
Nice Work !
Can We do this using PHP Curl ?
When I used Curl after some time url is expired, how can i fix this?
and room is not created in my panel but chat work fine below is my code :

`<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.eyeson.team/webhook",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"types\"\r\n\r\nroom_update\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--",
  CURLOPT_HTTPHEADER => array(
    "authorization: --***key***--",
    "cache-control: no-cache",
    "content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW",
    "postman-token: 635678b8-1971-49f2-c365-862f4d1ad626"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}`

**Comment by unused** [comment]
Hi! You can use any method to contact the API, have a look [on the request class](https://github.com/eyeson-team/eyeson-php/blob/master/src/Utils/Request.php#L41) to see how it is done in the package. A meeting link expires if no one joins so only join a room when someone wants to join (and redirect) and do not start a meeting upfront, there is no need to. Best wishes!

**Comment by yogesh-rinologix** [comment]
Thanks for reply and help me. There is one more concern if creating guest link why it auto fill name how can we fill the correct name using code

**Comment by unused** [comment]
If you already have the name of your participant you can simply add them to the room: use the same room identifier so your users will end up in the same meeting. For sure you can also use the [guest token](https://eyeson-team.github.io/api/api-reference/#user-and-guest-user) to join users but this is rather useful when inviting people within a meeting.
