### ISSUE TITLE
Embed Iframe doesn't recognize browser Firefox (works with Chrome)

### ISSUE THREAD

**Issue by hourlier96** [eyeson-team/eyeson-php#29]
Hi,
I'm currently working on a Vue.js interface calling Eyeson API in PHP to create a room.

It seems that when using Firefox, the embed iframe doesn't recognize the browser.
![Capture du 2020-07-17 13-40-04](https://user-images.githubusercontent.com/45850718/87782640-349fda00-c833-11ea-9070-44c7136ce628.png)

However, it's working perfectly with Chrome / Chromium.

Here is an extract of the iframe code. 
![Capture du 2020-07-17 13-46-14](https://user-images.githubusercontent.com/45850718/87783005-e7703800-c833-11ea-954b-1b3baf56b1c4.png)

I suppose it's not the expected behaviour.
Am I missing something in the iframe specification, or maybe in the Eyeson Documentation?

I'm working on Ubuntu 18.04.4
Thank you in advance

**Comment by unused** [comment]
Hi! We do not encourage the use of iframes for eyeson services. As you are working on a custom user interface there is anyways no need to use such. Please have a look on the [JS documentation](https://eyeson-team.github.io/js-docs/) as well as on the [custom UI example](https://github.com/eyeson-team/react-web-gui-example) to get more details on building you own frontend. Best wishes!
