### ISSUE TITLE
Custom close button

### ISSUE THREAD

**Issue by johnsoliman** [eyeson-team/eyeson-php#3]
Is it somehow possible to disable or provide a different link for the exit button. We would like to implement a custom close button, so that we can redirect the user back to our page. 

Is there a room option to do this, like show_label/recording_available/broadcast_available?
If not can we somehow provide a custom link for the close button or can you please implement something like this?

**Comment by unused** [comment]
Thank you for your feedback, the exit destination is already in configuration, but unfortunately not via the endpoint options. We'll adapt the options accordingly and update you when the feature has been released.

**Comment by unused** [comment]
The option is available at any room via `exit_url`.

**Comment by unused** [comment]
Sorry for the delay, the correct GUI already be available on all systems and the exit button accept the new configuration option.

**Comment by johnsoliman** [comment]
Thanks for that option, it works well, but I just have another question/request. Now if you join two different users to the same room, both users take the last exit_url you provide.

```
$eyeson = new \EyesonTeam\Eyeson\Eyeson(EYESON_APIKEY);
		$options = [
			'exit_url'	=> $myUrl,
			'recording_available' => false,
			'broadcast_available' => false,
			'show_label' => false,
		];
$r1= $eyeson->join($userData1, $roomName, $options1);
$r2= $eyeson->join($userData2, $roomName, $options2);
```
Even if I add both users in one array $userData both users take the same options and therefor the same exit_url. Is it somehow possible to provide every user with a different exit_url?
