### ISSUE TITLE
sample code

### ISSUE THREAD

**Issue by repzlaw** [eyeson-team/eyeson-php#30]
please can you give me a fully functional sample code in which eyeson has been fully integrated for testing because i dont understand the documentation

**Comment by repzlaw** [comment]
please code should be in php

**Comment by unused** [comment]
Hi, you can find an example of usage in the [README](https://github.com/eyeson-team/eyeson-php#usage) of this repository or have a look at the [API documentation](https://eyeson-team.github.io/api/getting-started/). What part of the documentation do you have troubles with?

**Comment by repzlaw** [comment]
sorry how do i run the README. I'm kind of new to this kind of thing

**Comment by repzlaw** [comment]
can you give me a walk through

**Comment by repzlaw** [comment]
i have downloaded the repository

**Comment by unused** [comment]
The [documentation](https://eyeson-team.github.io/api/getting-started/) and examples provide you with everything you need to get started. If you have any question about a specific feature or detail we're happy to help. Best wishes!
