### ISSUE TITLE
webhook updates

### ISSUE THREAD

**Issue by ragheeddamaj** [eyeson-team/eyeson-php#31]
Although i registered a webhook, but i am not receiving any updates 

example:
......
$eyeson->addWebhook('http://***receiveWebhook.php', ['user_update', 'document_update', 'recording_update','broadcast_update', 'room_update', 'team_update', 'presentation_update']);

and I verified that the webhook is registered at eyeson 

thank you

**Comment by unused** [comment]
see https://github.com/eyeson-team/api/issues/50 thanks!

**Comment by ragheeddamaj** [comment]
Main question (1):

Please check the following details about what I did, please let me know if I did any mistakes because it's urgent 

The below screenshot to verify that the webhook is successfully registered.

![image](https://user-images.githubusercontent.com/22028182/90265990-0b875f00-de5c-11ea-8aff-f20bf161d439.png)

I am logging the response to a file to see it response format, using the following code:

file_put_contents('webhookTest.txt', "requestedNEW " . $_POST . "\n", FILE_APPEND | LOCK_EX);

But no event triggered the file yet. even though, I did many meetings.

Question 2:
Also, a second question, after the webhook is successfully working. Does eyeson let me know when the participant enters the meeting and the duration, even if he enter and left many times?

Question 3:
 If webhook is stuck and still not working, do you have any API I can request to get when the participant enters the meeting with the duration, even if the user enters many times to the meeting?



Please i need your help ASAP.

**Comment by ragheeddamaj** [comment]
Dear, 

Does eyeson let me know when the participant enters the meeting and the duration, even if he enter and left many times?

Thank you

**Comment by unused** [comment]
We don't track the API users participants but you can easily build your own custom user interface and do so. Best wishes!
