### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#32]
Hi, I see this in the API Documentation:
![image](https://user-images.githubusercontent.com/4943143/90169607-d2bc8c80-dd6c-11ea-8e4d-bdc9f4f1b756.png)

Is there a french translation ? And if not, can we help creating it ?

**Comment by unused** [comment]
Thanks for the feedback and for the offer to help with translation. We currently do not offer additional languages however we've seen several requests on this but avoided adding more translations as it quickly outdates as we proceed with development. However we will have some discussion at the beginning of next week and I'm sure we will find some solution to this. I'll leave a comment as soon as I have any news :)

**Comment by unused** [comment]
I've published [a repository](https://github.com/eyeson-team/web-gui-locale) with our current locales. We will consider including the repository in our default web GUI with some upcoming release. Best wishes!

**Comment by malanciault** [comment]
AWE-SOME !!! We will add french translation soon !!
