### ISSUE TITLE
Custom logo

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#33]
Hi, I'm seeing this in the API Documentation:
![image](https://user-images.githubusercontent.com/4943143/90169786-131c0a80-dd6d-11ea-8e21-3f2891a0b002.png)

2 questions.

1- Where would this logo be displayed ?

2- I tried this bit did not see the custom logo:

$options = array(
            'show_names' => 'show',
            'show_label' => 'false',
            'reaction_available' => false,
            'exit_url' => site_url(),
            'logo' => $logo_url,
        );

Thanks for your help !

**Comment by unused** [comment]
I've added the option, should be fine now. The logo is replaced on the top left corner.

**Comment by malanciault** [comment]
Great, thanks!

**Comment by kvvaradha** [comment]
this is a great stuff from the eyeson team. 

hopefully, if you extended the API with loading animation and color scheme option like custom color scheme, it would be great feature for us.

**Comment by unused** [comment]
Thank you for the feedback. We currently do not support such configurations and have no customization for the provided default web UI on our roadmap. However you can easily create your own custom user interface, which has almost no limitations. You can find more details in the [documentation of the eyeson JavaScript package](https://eyeson-team.github.io/js-docs/) that helps you get started quickly.

**Comment by kvvaradha** [comment]
thank you. will go with react ui build level
