### ISSUE TITLE
What's the correct procedure to record a meeting and get the URL of the video file

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#34]
Hi,

We are doing something like this:

```
$eyeson = new Eyeson($api_key);
        $options = array(
            'show_names' => 'show',
            'show_label' => 'false',
            'reaction_available' => false,
            'exit_url' => $exit_url,
            'logo' => $logo,
            'recording_available' => true,
            'broadcast_available' => false,
            'layout_available' => false,
        );
	$room = $eyeson->join($firstname, $id_of_room, $options);
        $recording = $eyeson->record($room);

	redirect($room->getUrl());
    }
```

So the user is redirected to the room url and the recording starts.

What is the best way to stop the recording and get the URL of the video file ? Is it via a webhook? Would you have an example ?

Thanks!!

**Comment by unused** [comment]
Hi there, as the recording is not ready at the time the user stops it (postprocessing & uploading to our cloud storage) the best way to manage recordings is to use [webhooks](https://eyeson-team.github.io/api/api-reference/#register-webhooks). Let me know if you have any further questions on this!
