### ISSUE TITLE
Layers not working

### ISSUE THREAD

**Issue by mccarlosen** [eyeson-team/eyeson-php#35]
I have created a room and I am testing the layers, but nothing happens. I am using laravel 7.

```php
Http::post('https://api.eyeson.team/rooms/:access-token/layers', [
    'url' => 'https://eyeson-team.github.io/api/images/eyeson-overlay.png',
    'z-index' => 2,
    'layout' => 'fixed'
]);
```

Lastly, I have tried with eyeson-js

```js
onEvent({
    type: 'set_layer',
    params: {
        url: 'https://eyeson-team.github.io/api/images/eyeson-overlay.png',
        'z-index': '2',
        layout: 'fixed'
    }
})
```

![image](https://user-images.githubusercontent.com/8524361/91376502-cca1c380-e7e2-11ea-9c36-07b59d406649.png)

**Comment by mccarlosen** [comment]
Excuse me, I already saw the duplicate #22

**Comment by mccarlosen** [comment]
Hello again,

I have created a room with option `'sfu_mode' => 'disabled'` and I am testing the layers, but nothing happens. I am using laravel 7.

```php
$eyeson = new Eyeson($apiKey);
    $room = $eyeson->join($userName, $roomName, [
    'sfu_mode' => 'disabled'
]);

Http::post('https://api.eyeson.team/rooms/:access-token/layers', [
    'url' => 'https://eyeson-team.github.io/api/images/eyeson-overlay.png',
    'z-index' => 2,
    'layout' => 'fixed'
]);
```

Lastly, I have tried with eyeson-js

```js
onEvent({
    type: 'set_layer',
    params: {
        url: 'https://eyeson-team.github.io/api/images/eyeson-overlay.png',
        'z-index': '2',
        layout: 'fixed'
    }
})
```

I have created another user for the test, so that they are 2 and nothing. What am I doing wrong?

**Comment by unused** [comment]
Hi there, please replace the `:access-token` in your URL with a valid access key, it's meant as a placeholder and otherwise there is no auth given. In your PHP example it's something like `Http::post('https://api.eyeson.team/rooms/' + $room->getAccessKey() + '/layers', // ...`. Best wishes!
