### ISSUE TITLE
Adding animations and videos with layers

### ISSUE THREAD

**Issue by mccarlosen** [eyeson-team/eyeson-php#36]
Based on the information on the page, do you have an example to achieve this?

![image](https://user-images.githubusercontent.com/8524361/91470796-c8b18800-e85a-11ea-9000-ea2f4766aef9.png)

**Comment by unused** [comment]
Thank you for the feedback, we have provided the video inject as experimental feature for quite some time now and just decided to add it to the documentation with an upcoming release. You can check the default web GUI (gif & emoji reactions) on how to use it for now. I'll leave some comment when the documentation has been update.

**Comment by unused** [comment]
The [media inject document section](https://eyeson-team.github.io/api/api-reference/#content-integration-aka-layers) has been updated with details for playbacks. Best wishes!
