### ISSUE TITLE
Share audio with screen sharing

### ISSUE THREAD

**Issue by mccarlosen** [eyeson-team/eyeson-php#37]
How can I take advantage of this chrome and edge feature with Eyeson.

![DeepinScreenshot_Seleccionar área_20200827164655](https://user-images.githubusercontent.com/8524361/91498536-89e4f780-e885-11ea-8e5f-8dc65c0d91e0.png)

I have added `audio: true` to enable the `Share audio` option. But it is not heard in the remote video.

```js
getDisplayMedia() {
    if (FeatureDetector.hasGetDisplayMedia()) {
      return navigator.mediaDevices.getDisplayMedia({
        audio: true, // new line
        video: {
          width: { max: 1920 },
          height: { max: 1080 },
          frameRate: { max: 15 }
        }
      });
    }
    // .........
}
```

But doing it like this it works

```js
let videoElement = document.querySelector('video');
let audioElement = document.querySelector('audio');

let audioTrack, videoTrack, stream; 
window.navigator.mediaDevices.getDisplayMedia({video: true, audio: true})
.then(async displayStream => {
    videoElement.srcObject = displayStream;
    videoElement.play();
})
.catch(console.error);
```

**Comment by opusonline** [comment]
Hi. Thanks for your feedback!
Unfortunately it's a bit more complex to add system audio in our application.
This feature is currently not supported.
Best regards,
Stefan
