### ISSUE TITLE
The request has failed for an unhandled reason

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#39]
Hi, we are getting this error:

> Sep 03 15:49:12 b63b468e-ddd3-4501-872b-03367b5141eb php: ERROR: Severity: error --> Exception: Request failed. The request has failed for an unhandled reason. If you expect an error feel free to create an issue for the project anytime. 

Here is the code:

```
        $eyeson = new Eyeson('xxx');
        $options = array(
            'show_names' => 'show',
            'show_label' => 'false',
            'reaction_available' => false,
            'exit_url' => 'xxx',
            'logo' => 'xxx',
            'recording_available' => true,
            'broadcast_available' => false,
            'layout_available' => false,
        );
	$room = $eyeson->join('xxx', 'xxx', $options);

        $eyeson->addWebhook('xxx', 'recording_update');
        $eyeson->addWebhook('xxx',, 'room_update');
        $recording = $eyeson->record($room);

	redirect($room->getUrl());
```

Now, when the error occurs the first time this code is executed. Then, if we run it a second time, the room is created and it works. When we close the room, if we execute this code again, it will generate an error, and then we reload it and it will work.

What are we missing?

Thanks!

**Comment by unused** [comment]
Hi! It looks to me like the error message comes from the framework in use - there is no hint what fails, from your code I'd expect that it fails as you try to start a recording for a meeting that is not yet ready. Please ensure the meeting is up and running before starting a recording. Please also ensure that you only register **a single webhook** - this will receive data of **all** rooms. In your example it is also enough to use just `room_update` as recordings will be part of it. Let me know if you need any further help, best wishes!

**Comment by malanciault** [comment]
OK thanks. Now I'm only registering one webhooks, but I don't seem to receive updates about recording, as I was receiving when I also had a webhooks for update_recording. Can you help ?

**Comment by unused** [comment]
You can add multiple resources types as a comma separated list, e.g. `$eyeson->addWebhook('xxx', 'room_update,recording_update')`.
