### ISSUE TITLE
Disable chat

### ISSUE THREAD

**Issue by johnsoliman** [eyeson-team/eyeson-php#4]
Similar to my last request about the custom exit button, we would like to disable the chat option in the web GUI. Is this somehow possible?

**Comment by unused** [comment]
There is no configuration to hide or disable the chat and no such option planned. The chat provides a convenient way to communicate when someone is muted or has troubles with any device, and supports other features like notifications or webinar questions.
The eyeson web GUI implements many of the features provided by the eyeson API service. If you want to limit the user interface, for sure you can also create your own custom appearance. Note that as we constantly improve and extend the eyeson web GUI you might miss out new features with a customized user interface.
