### ISSUE TITLE
This link has passed away. Please contact the host of the video call to get access.

### ISSUE THREAD

**Issue by vinayakmint99** [eyeson-team/eyeson-php#41]
I have created a meeting programmatically by php api and simultaneously create a guest link then I have stored both links.  When I used the admin link to start the meeting then I got the error message like " The link has passed away".

The code is given below which I am using for create both links :-

define('__ROOT__', dirname(__FILE__));
require_once(__ROOT__.'/vendor/autoload.php');

use EyesonTeam\Eyeson\Eyeson;

$eyeson = new Eyeson('xxxxxxxxxxxxxxxxxxxxxxxxxxx');

//$room = $eyeson->join($userconf, 'Anytime Video Consult');

$options = [
      'show_names' => true,
      'show_label' => true,
      'exit_url' => 'https://www.eyeson.team/',
      'recording_available' => true,
      'broadcast_available' => true,
      'layout_available' => true];

$room = $eyeson->join($userconf, null, $options);
$eyeson->getLayout($room)->showNames();

$doctor_conf_url_api    =   $room->getUrl();
//

$patient_conf_url_api   =  'https://app.eyeson.team/?guest='.$room->getGuestToken();

**Comment by unused** [comment]
Please note that a meeting will expire quite soon if no one joins it. Therefor only request a URL for your users when they are ready to join and forward them directly. Do not hesitate to leave a comment if this did not solve your problem. Best wishes!
