### ISSUE TITLE
skillMeeting Locale

### ISSUE THREAD

**Issue by skillexia** [eyeson-team/eyeson-php#43]
am still testing your API and can't get "locale" to work when creating a room This is my PHP code: $options = ['name'=>$location_info['location_name'], 'custom_fields'=>['locale'=>'fr'], 'suggest_guest_names'=>false, 'exit_url'=> HTTPS.SERVER_NAME.'/admin/meetings/close' ]; $room = (array) $eyeson->join($user,$location_id,$options); The room is created correctly and works fine but it's always in English and we also have French clients. Thanks

**Comment by unused** [comment]
You can skip the `custom_fields` prefix and use `$options = ['locale' => 'fr']` instead. Best wishes!

**Comment by skillexia** [comment]
> You can skip the `custom_fields` prefix and use `$options = ['locale' => 'fr']` instead. Best wishes!

This doesn't work:

$options is:
Array (
[name] => michel.2501.cooking string
[locale] => fr string
[suggest_guest_names] => boolean
[exit_url] => https://demo.skillmeeting.com/admin/meetings/close string
)
$room = (array) $eyeson->join($user,$location_id,$options); 

The room is still in english
![snap1](https://user-images.githubusercontent.com/72741916/95750371-54f9fc00-0c9d-11eb-96d3-758148913497.jpg)

**Comment by skillexia** [comment]
ok. uploaded the newest PHP api. Works.
