### ISSUE TITLE
Screen sharing problem

### ISSUE THREAD

**Issue by mccarlosen** [eyeson-team/eyeson-php#46]
What is this about? Bandwidth? I have a connection of 100MB.

![image](https://user-images.githubusercontent.com/8524361/98393979-16e7c200-2028-11eb-8d44-e72a8ee299ef.png)

![image](https://user-images.githubusercontent.com/8524361/98394266-7e9e0d00-2028-11eb-8c67-e9be341eac8e.png)

**Comment by unused** [comment]
Hi there, thank you for the screenshots. Can you share some further details with us: What browser and operating system did you use? Did your screen capture session result constant pictures as shown on the screenshots or are those examples of bad ones? Tia!

**Comment by mccarlosen** [comment]
I have an app that uses Eyeson PHP and Eyeson JS. When I share a screen, the users in the room see that.

We use Chrome 86, Windows and others use Linux, they all look like this. Screenshots are taken in real time.

**Comment by unused** [comment]
Thank you for the details. Can you please check if you have the same issue when using the default web-gui or even better the example [hosted on GitHub](https://eyeson-team.github.io/react-web-gui-example/)? You can start any meeting using [accounts.eyeson.team](https://accounts.eyeson.team/) for this check, no need to use your API access. Thank you in advance!
