### ISSUE TITLE
H1 of the page (Name of thew account)?

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#48]
Hi,

When creating a room, how to change the H1 of the page ? I thought it was the name of my account on Eyeson.com but I changed it and it does not reflect.

![image](https://user-images.githubusercontent.com/4943143/98699250-ef089f00-2344-11eb-9020-67f8e01dda64.png)

Thanks

**Comment by unused** [comment]
You can change the title using a proper room name like:

```sh
curl -X POST \
  -H "Authorization: $1" \
  -d "user[name]=demo" \
  -d "name=Room Name" \
  "https://api.eyeson.team/rooms"
```

**Comment by malanciault** [comment]
OK, would it work with :

`$eyeson->join($user, 'daily standup');`

**Comment by unused** [comment]
There was a mistake, the room name option was missing. The string `daily standup` in your example is the identifier, which ensures all participants end up in the same meeting. However the name is independent from this one and allows to set a readable name for the room. I just added the missing option ...  `$room = $eyeson->join('tester from eyeson-php', null, ['name' => 'Daily Standup']);`
Best wishes!

**Comment by malanciault** [comment]
Ah ! It works great! Thanks, you rock !
