### ISSUE TITLE
Room link expiration time

### ISSUE THREAD

**Issue by johnsoliman** [eyeson-team/eyeson-php#5]
We tested our application and sometimes encountered a "RIP - Link is dead" error. It seems like the room link expires under 10 minutes? What is the exact time that a room link is available after creation?

**Comment by unused** [comment]
Thank you for your question - when you join a room, but don't enter it afterwards the room will be closed after a timeout of 2 minutes. How is your application managing the user interaction to join a room? The common case is, to send the user and room information to the API when the user decides to enter, then directly redirect to the web interface. Does your software join the user before the action to enter the room takes place?

**Comment by johnsoliman** [comment]
Okay, that's good to know, but what if someone joined a room, and patiently stays in the room while the other user is late. Let's say I created his link also 2 minutes before the first person joins the room. Is his generated link still available after 10 minutes for example?

The application currently creates the link before the user tries to join.

**Comment by unused** [comment]
That's no problem - the shutdown timer is only active per room and if there are no users connected.

Let me know if you have any other question on this.

**Comment by johnsoliman** [comment]
How is the expiration timeout handled according to pricing. Usually pricing is per video minute; does the 2 minute timeout, when no one is in the room, count into that? I guess if one user is in the room, every minute he remains there counts, even though the other user might never join the room.
Thanks for clarifying...

**Comment by unused** [comment]
If you have any question regarding plans and pricing, please refer to our [help center](https://help.eyeson.team/) or contact our support.

**Comment by agavitalis** [comment]
Please can this 2mins timeout be increased?

**Comment by unused** [comment]
Hi! There should be no reason to care about the limit in first place. The timeout just ensures any meeting gets closed if no one ever joins it. Just ensure you only contact the eyeson service as soon as your user wants to join a meeting. If you need any kind of invitation link it's best to handle this in your application. There you can also manage authentication, authorization, expiration and many other things. Please do not hesitate to create an issue or leave a comment if you have any further questions. Best wishes!

**Comment by agavitalis** [comment]
My team is working on an application that involves video call, and we are using your solution,  when a user generates the room link, and the other invitees didnt join on time, If the host mistakenly logs out while trying to reach out to the invitees, on trying to log in.... It shows meetting link have passed away. 

Is there an option to pass durring to room creation to increase the expiration time...I have. gone through your docs but I cant seem to find any

**Comment by unused** [comment]
Never think of the expiration, there is no need to take care of this. If you join your users from within your application the eyeson services will take care there is always a meeting ready for your participants. Do not use the URLs received from the eyeson API to invite your users but generate your own. [Use a unique room identifier](https://eyeson-team.github.io/api/api-reference/#eyeson-room) (`id` parameter) so the participants join the same meeting. Do not hesitate to leave a comment if you still have any troubles. Best wishes!

**Comment by agavitalis** [comment]
According to the docs, if the ID isn't passed, one will be generated for me. The major challenge is that the meeting link expires even before its used. Even when the users have a little network challenge, it expires before they could join back. Is there no way for me to specify the expiration time??

**Comment by unused** [comment]
Please do not worry about the expiration time at all. This is just a internal mechanic at the eyeson service that does not influence working with the API as long as you do not use the access key (or web GUI link) to invite people. The access key (or GUI link) serves as a temporary authentication for your user and has to expire after a short period of time. If you need to invite people, do so by creating a proper way in your application and **only** request the eyeson API when a user is joining/starting a meeting. If there is a connection issue, the participant will receive a proper error page and have to possibility to return to your application and join again (best practice is to set a proper `exit_url`). In case the current meeting is gone (no other participants were left), a new one will get started which is in-transparent for your user, she will always **just join** the meeting again.
