### ISSUE TITLE
Webhook was deleted

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#50]
Hi,

We have integrated our platform with Eyeson and are heavilyusing the webhooks. Everything has worked fine since the begining (+-2 months ago) and then the webhook stoped to be triggered. We did a GET https://api.eyeson.team/webhooks to check what was the last time it was triggered and got a null response.

So we recreated the webhook. Now it's working.

Would there be any reason the webhook would be deleted on your end, other than a DELETE request on our end ?

**Comment by unused** [comment]
Hello, thank you for the information. We do not remove webhooks at any place but I'll double check if I can figure out if there has been any mistake.

**Comment by malanciault** [comment]
Thanks, much appreciated!

**Comment by malanciault** [comment]
Hi, any update on this ? And more importantly, is there a way to restore the many recordings that we were not able to catch before of this. Thanks

**Comment by unused** [comment]
Hello, there is no process that removes client Webhooks in our service. For sure we extended our monitoring details on this section, additionally there is WIP on improving transparency for this feature.
We can for sure re-trigger the webhooks. I'll reach out to support so they contact you when you are ready to receive the data!

**Comment by malanciault** [comment]
Just to say: Thank you :) You guys are awesome!

**Comment by unused** [comment]
Thank you we are happy that we could help and I'll forward your feedback to the team :)
