### ISSUE TITLE
Question concerning link livetime

### ISSUE THREAD

**Issue by LK1one** [eyeson-team/eyeson-php#51]
How long are room links valide after creation? 5 Minutes? Can we lengthen the lifetime? Thanks

**Comment by LK1one** [comment]
Found this problem on solved issues here. So I'm not able to pre-create links. I have to create them when someone wants to join.

**Comment by unused** [comment]
Yes, you're very right! As soon as a user joins we ensure a video conference is available for this participant, therefore you don't have to create anything upfront using the eyeson API service but can handle any user related management (like authentication for specific meetings) in your application.
