### ISSUE TITLE
Multiple broadcast simultaneously

### ISSUE THREAD

**Issue by alamgira** [eyeson-team/eyeson-php#53]
Hello, 
Is it possible to stream to multiple rtmp url simultaneously (for example facebook and youtube). I am currently using eyeson php library to broadcast. Can I initiate two broadcast

**Comment by unused** [comment]
Hi there! You can use a re-streaming platform to forward your video and audio to multiple platforms or [contact our sales team](https://www.eyeson.com/contact-sales/) if you need a solution at large scale through the eyeson platform. Best whishes!
