### ISSUE TITLE
iframe chrome 88

### ISSUE THREAD

**Issue by juliengriffonwinwin** [eyeson-team/eyeson-php#57]
Hi,

Since Chrome update (Version 88), camera/microphone does not work in iframe integration

Same code as before:

<iframe
            style="width: 100%; height: 100%; border: none; left: 0px; position:absolute;"
            frameborder="0"
            :src="visio"
            allow="microphone https://app.eyeson.team; camera https://app.eyeson.team"
            allowfullscreen
          />

**Comment by unused** [comment]
Hi there! We do not see any issue with Chrome v88 (win, osx), can you please provide some details? Your snippet seems to have some mistake in it `:src="visio"`.

**Comment by juliengriffonwinwin** [comment]
Hi !

the version : Version 88.0.4324.96 (Build officiel) (x86_64)

iframe exemple :
<iframe frameborder="0" src="https://app.eyeson.team/?GTm3mGdBw4hfxCvSPpw1JpuF" allow="microphone https://app.eyeson.team; camera https://app.eyeson.team" allowfullscreen="allowfullscreen" style="width: calc(100% + 72px); height: 100%; border: none; left: 0px; position: absolute;"></iframe>

The new chrome version refuse the permission

DeviceManager:: DOMException: Permission denied

**Comment by unused** [comment]
Unfortunately we cannot reproduce this issue, so just to get sure can you check if the error also occurs when using a private window where permissions are re-checked?
