### ISSUE TITLE
How to disable end meeting for all button in php

### ISSUE THREAD

**Issue by aycw2526** [eyeson-team/eyeson-php#58]
`$options = array(
            'show_names' => 'show',
            'show_label' => 'false',
            'reaction_available' => false,
            'exit_url' => site_url(),
            'recording_available' => false,
            'broadcast_available' => false,
            'layout_available' => false,
            'name' => Example,
        );

        $user = [
          'id' => $user_id,
          'name' => test test,
        ];`

Is there an option to disable the button?

**Comment by opusonline** [comment]
Hi,
thanks for your feedback!
Currently there's no option to disable this button, but we will discuss your request.
(Good to know: guests do not have this button.)
Please do not hesitate to open another issue or leave a comment if you have any further questions!
Best regards, Stefan
