### ISSUE TITLE
Is it possible to automate a message in the chat?

### ISSUE THREAD

**Issue by aycw2526** [eyeson-team/eyeson-php#59]
Hi, is it possible to automate a message that will be sent to the chat with a specific time?
For example, if I want to send a message "hello everyone!!!" in the chat automatically  at 8am.

**Comment by opusonline** [comment]
Hi,
this is possible, but on your side!
Simply set up a function in your app that sends a chat message using the API (https://eyeson-team.github.io/api/api-reference/#messages) on a specific time.
Please do not hesitate to open another issue or leave a comment if you have any further questions!
Best regards, Stefan

**Comment by aycw2526** [comment]
Hi,
I looked in the API documentation, but I can't figure out how it works.
Could you provide a valid example of message sending in the chat in php please?

Best regards

**Comment by unused** [comment]
You can [send messages](https://eyeson-team.github.io/api/api-reference/#messages) to any room but it requires authorization via access key (create an additional user if required).

```
$ ACCESS_KEY=... curl -X POST -d "type=chat" -d "content=good morning" "https://api.eyeson.team/rooms/$ACCESS_KEY/messages"
```

Note that the access key is the authorization secret for a specific user for any meeting session, not your eyeson api token.
