### ISSUE TITLE
Custom user interface

### ISSUE THREAD

**Issue by johnsoliman** [eyeson-team/eyeson-php#6]
As we need to reduce several components of the user interface we would want to build a custom user interface if somehow possible. Unfortunately I can't find anything in the documentation on how to connect to the websocket or how to use it accordingly. How can I create a valid connection to the video/audio stream and embed it and close a room using the websockets?

**Comment by unused** [comment]
That's great, let me point you to the right directions: To create your own interface please refer to the [JavaScript library documentation](https://eyeson-team.github.io/js-docs/), there is also a [tutorial project](https://github.com/eyeson-team/react-web-gui-example) that uses React, but any other Framework is fine. For sure you can also use native JavaScript as described in the documentation.

**Comment by johnsoliman** [comment]
Thanks for the links, I wanted to download the Javascript library, but there is no library in that download - only the documentation.

**Comment by unused** [comment]
You can use the [JavaScript library hosted on npm](https://www.npmjs.com/package/eyeson). If you have any further questions do not hesitate to create an issue!
