### ISSUE TITLE
composer eyesone/eyeson-php command download empty eyeson-php directory inside vendor directory

### ISSUE THREAD

**Issue by aryaashwani28** [eyeson-team/eyeson-php#61]
there is some issue with code files because "composer eyesone/eyeson-php" download all files:
vendor
composer.json , lock files but the eyeson-php directory is empty ? composer is unable to fetch files inside eyeson-php folder i have to manually download the zip files.

**Comment by opusonline** [comment]
Hi,
thanks for your feedback!
We will investigate and get back to you later.
Best regards, Stefan

**Comment by unused** [comment]
You can check the [Dockerfile](https://github.com/eyeson-team/eyeson-php/blob/master/Dockerfile) that uses composer to install dependencies for the unit tests of this package. If you are unsure how to use [composer please read its documentation](https://getcomposer.org/doc/).
