### ISSUE TITLE
Webhook type user_update

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#62]
Hi, 

We have a webhook setup for types room_update, recording_update and user_update :

![image](https://user-images.githubusercontent.com/4943143/108197111-ed8b0780-70e7-11eb-840c-a1cab65a1647.png)

We do receive all room_update and recording_update but we seldom receive user_update. I did not quite find the exact pattern for when we do receive them though. 

Here is an example: 

We join a user to a new room and redirect him to the room URL

```
$room = $eyeson->join($user, $room_name, $options);
redirect($room->getUrl());
```
The user activate is cam and mic and join the room. Stays for 30 seconds, than close the room for all.

The webhooks we receive are as follows:

1- type: room_update
room:
    id: consultation-1-production
    name: Clinique virtuelle Medicart
    ready:
    started_at: 2021-02-17T11:23:56.103Z
    shutdown:

2- type: room_update
room:
    id: consultation-1-production
    name: Clinique virtuelle Medicart
    ready: 1
    started_at: 2021-02-17T11:23:56.103Z
    shutdown:

3- type: room_update
room:
    id: consultation-1-production
    name: Clinique virtuelle Medicart
    ready:
    started_at:
    shutdown: 1

We did not receive any user_update.

Perhaps we receive user_update only with the second user joining ?

Question:

1- Can you specify what action should trigger a user update ?

2- What is the best way to detect when people are leaving the room ?

Thanks!

**Comment by unused** [comment]
Thank you for reaching out. Our support team will contact you. The `user_update` is a legacy method that will not work properly in some cases, we will update our documentations asap.
