### ISSUE TITLE
Can you provide a sample to use the 3rd parameter to pass the logo, exit_url, etc

### ISSUE THREAD

**Issue by kvvaradha** [eyeson-team/eyeson-php#63]
Hi 

First of all, This is wonderfull app to try with simple api functionality.  thank you for making wonderful stuff easier to users. 

As i am trying to figureout the way to pass the 3rd  argument, the configuring options from api call. 

`
require_once('eyeson/vendor/autoload.php');

use EyesonTeam\Eyeson\Eyeson;

$eyeson = new Eyeson('CBsQh2sTzsj34RevuQ2a5iXh3EgHd1CAa8ThzmCTof');
$room = $eyeson->join('Myname', 'Test', ['logo' => 'https://example.com/favicon.png']);

echo 'URL to eyeson GUI ' . $room->getUrl() . "\n";
`

I didn't understand with 3rd parameter.   thank you in advance

**Comment by unused** [comment]
Hi there, first of all I have to ask you to regenerate your API key. It is a secret and should never be shared. Your options look fine, did you ensure to use a public available logo image file? You can check all [available options](https://github.com/eyeson-team/eyeson-php/blob/master/src/Resource/Room.php#L26) and find further details in the [API documentation](https://eyeson-team.github.io/api/api-reference/#eyeson-room). Let me know if you have any further questions.
