### ISSUE TITLE
Firewall, IP

### ISSUE THREAD

**Issue by juliengriffonwinwin** [eyeson-team/eyeson-php#64]
Hi,
On a customer's network, we performed eyeson compatibility tests.
https://app.eyeson.team/quicktest/

But one IP is not in the system requirement list.
https://help.eyeson.com/eyeson-system-requirements

IP : 109.70.102.200
We are asked if it belongs to you, what is it used for, and why it's not in the system requirement lists ?

Cordialy!

**Comment by unused** [comment]
Hi there! The requirements in the help center describes a common solution to ensure outbound traffic for TURN servers, which in case they are blocked should be allowed at least for UDP traffic to ensure quality of service. All other endpoints are addressed via TLS/443 which is very unlikely to be blocked even in restrictive company networks. We do not document a static list of IP addresses on those as they are likely to change. Please do not hesitate if you need any further information. Best wishes!
