### ISSUE TITLE
Per user options 

### ISSUE THREAD

**Issue by lucasromanojf** [eyeson-team/eyeson-php#65]
Hello,

Is there a way of setting per user options for a same room? For example, I'd like the first user to have recording access but the other users not. 

Tried creating two different tokens using different options but the last request overrides the room options globally, for all users.

I created a teacher token setting recording option to true. Then I created a student token setting recording option to false, but after that the teacher was not able to record anymore too. 

Thanks!

**Comment by unused** [comment]
Hi! We currently do not provide any user roles/access rights. If you need such we suggest to create a custom UI and proxy control through your application server to apply policies.
However I'll forward your requirement to our planning sessions and check if we add this to our features to work on. Best wishes!
