### ISSUE TITLE
Virtual Background

### ISSUE THREAD

**Issue by malanciault-illuxi** [eyeson-team/eyeson-php#67]
Hi,

I'm trying to use the new virtual_background option but I'm never seeing the select box to choose the background.

I'm passing the virtual_background option to true: https://illuxi.d.pr/B7crGM

What am I missing ? Thanks!

**Comment by unused** [comment]
Hi there, I'll look into this issue asap, seems there is an issue with converting the parameter values.

**Comment by unused** [comment]
Should work fine now with the latest update `$room = $eyeson->join('tester from eyeson-php', null, ['virtual_background' => true]);`. Best wishes!

**Comment by malanciault-illuxi** [comment]
Hi, unfortunately, it is still not working. See here: https://illuxi.d.pr/W7Kx7z

I am indeed passing ['virtual_background' => true]

What am I missing ?

**Comment by unused** [comment]
Can you please check if you are using the latest version of the package (v1.5.0)? I checked again and it works fine, adapted the [example](https://github.com/eyeson-team/eyeson-php/blob/master/example.php?plain=1) file.

```php
<?php

/**
 * Test script, run with `$   php example.php <api-key>`. Keep your cli history
 * clean, use extra spaces or clear afterwards ;)
 **/
define('__ROOT__', dirname(__FILE__));
require_once(__ROOT__.'/vendor/autoload.php');

use EyesonTeam\Eyeson\Eyeson;

$eyeson = new Eyeson($argv[1]);
$room = $eyeson->join('tester from eyeson-php', null, ['virtual_background' => true]);

echo 'URL to eyeson GUI ' . $room->getUrl() . "\n";
```

**Comment by malanciault-illuxi** [comment]
You were correct, package had not been updated, sorry. Now it works :) 

Another thing: I added a virtual_background_image which value is an URL with an image. When I open a room, I can select  the "custom image" but it does not work. See here: https://illuxi.d.pr/91LpLe

What am I missing ? Thanks!

**Comment by unused** [comment]
Thank you for the feedback, our UI team has tracked this issue down to an error in the selection and will fix it soon. I'll leave a comment when done!

**Comment by unused** [comment]
The web UI has been update, you can now set the custom image by URL. Please ensure `Access-Control-Allow-Origin` headers are set properly. Best wishes!

**Comment by malanciault-illuxi** [comment]
Working perfectly thanks!
