### ISSUE TITLE
sfu_mode not available in Ressource/Room

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#68]
Hi, 

Is it possible to add sfu_mode in the CONST OPTIONS of Ressource/room.php ? Without this, we cannot configure sfu_mode when creating a room using eyeson-php.

Let me know !

**Comment by unused** [comment]
Thank you, the missing option has been added: `$eyeson->join('demo', null, ['sfu_mode' => 'disabled']);`
