### ISSUE TITLE
Bug with the share screen during call

### ISSUE THREAD

**Issue by PaoloBoniccoBtB** [eyeson-team/eyeson-php#69]
Hello,
my users report me a bug: some of them aren't able to share their screen during the call on eyeson. Most of the times it happens on Safari, but Chrome yesterday report me this error while i was trying to share my screen: missing "an.error_Screen_SecurityError".
I don't know if this problem come from eyeson or from the browser settings, any advice?
Thanks for help

**Comment by unused** [comment]
Hi there! Thank you for the feedback, can you give me any details of the Operating System and Browser versions that present this error?
