### ISSUE TITLE
PHP SDK enhancement

### ISSUE THREAD

**Issue by flodi** [eyeson-team/eyeson-php#7]
I've seen the PHP SDK at the moment do not implement directly the APIs to manage overlays or to get calls recordings.

But I've seen there is a very clean implementation of the Request and Response object for Eyeson API calls, so I'm thinking about using them directly to call the APIs I need.

Do you think this is something doable or do you have other suggestions?

Thank you

**Comment by unused** [comment]
Thanks for reaching out, for sure you can use the interface provided to control recordings and layers. A common use case is to control recording and layers on the client-side of the meeting. This is already provided by the eyeson web GUI or the [JavaScript package](https://eyeson-team.github.io/js-docs/) for custom web user interfaces. Do you need the controls on server-side?

**Comment by flodi** [comment]
Hi, thank you vey much for the answer.

I try to explain better what I need to do:
- two guys receive and email with a link
- the first that click enter our platform, create and join a eyeson room 
embedded in our page (through iframe at the moment)
- wait for 5 minutes, if the second guy to not join, close the room, 
show a message
- when the second guy click, join the room, the two start talking, I 
start counting 20 minutes
- finished the 20 minutes I ask if they want another 20 (if yes I keep 
counting)
- if no I close the room, show a message to both and get the recording 
of the whole call to keep in the platform

At the moment I'm doing everything server side, mostly because the JS 
lib seems simple, but I didn't understood how to include it in my 
platform.

Managing the registration, opening, closing the room is mandatory, of 
course. asking to continue I can do on my page that embed eyeson, but 
I'd like to try to do that through layers.

 From what I'm reading, JS should be the way to go, right?

On 16 May 2019, at 8:25, Christoph Lipautz wrote:

> Thanks for reaching out, for sure you can use the interface provided 
> to control recordings and layers. A common use case is to control 
> recording and layers on the client-side of the meeting. This is 
> already provided by the eyeson web GUI or the [JavaScript 
> package](https://eyeson-team.github.io/js-docs/) for custom web user 
> interfaces. Do you need the controls on server-side?
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eyeson-team/eyeson-php/issues/7#issuecomment-492934549



--
Fabrizio Lodi
e-Scientia
R&D

**Comment by unused** [comment]
Sounds great, thank you for the insights.

I added handlers for start-/stopping a recording to the PHP library, as well as a method to force shutdown a running meeting.

For sure you can query your user in your application when showing the meeting only in an iframe. The layers service provides a convenient way to insert media (like background images, presentations, animations, watermarks, logos, messages, etc.), however there is no channel to receive any user interaction through this.

For a more controlled way on client-side and better integration, you can use the [eyeson JavaScript](https://www.npmjs.com/package/eyeson) package (see npm or yarn) that can be used with any framework or vanilla JavaScript to build a custom GUI.

Do not hesitate to leave a comment if you have any questions.
