### ISSUE TITLE
Lost custom background

### ISSUE THREAD

**Issue by malanciault** [eyeson-team/eyeson-php#70]
Hi, 

We were using a custom virtual background and it is not available anymore:

https://illuxi.d.pr/VOytC2

Nothing change in our code. Can you have a look ? Thanks!

**Comment by unused** [comment]
Hi, thank you for the heads-up. Our developers had a look and found an issue with the options, a fix has already been deployed. Can you confirm its again working for you? Thank you in advance.

**Comment by malanciault** [comment]
Yes, working. Thanks !
