### ISSUE TITLE
$response->getStatus() === 0

### ISSUE THREAD

**Issue by salmanaliawann** [eyeson-team/eyeson-php#71]
I am trying to create a room and receiving this error. Can you please look into this matter. Below is the error statement. Thanks in advance.

Network error. Please check your network connection and ensure the api target is reachable. If you receive this error in test-mode, you might have set a bad target api endpoint. Don't set a target URL in production.

**Comment by unused** [comment]
Hi there, can you please add some detail on how you start the meeting? Does running [the example](https://github.com/eyeson-team/eyeson-php/blob/main/example.php) with `$ php example.php <you-api-key>` result in the same error for you?

**Comment by salmanaliawann** [comment]
$eyeson = new Eyeson('key'); // works fine
$room = $eyeson->join('user'); // generates error
$room->getUrl(); // unreachable due to error

**Comment by unused** [comment]
Can you ensure your environment is properly configured to access public network? E.g. using `$ curl -I https://api.eyeson.team` should result in a HTTP response with a status code of `404`. Can you confirm this does provide a proper result?

**Comment by salmanaliawann** [comment]
$url = "https://api.eyeson.team";
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_URL, $url);
        $result = curl_exec($ch);
        
        I have tried this code and it is returning false as result.

**Comment by unused** [comment]
Unfortunately this does not give a clue about your problem. Can you run `$ curl -I https://api.eyeson.team` on a command line inside your environment (server)?

**Comment by salmanaliawann** [comment]
Please look into the attached file.
![image](https://user-images.githubusercontent.com/46898881/145575339-524eed50-2ede-41bb-a8ed-90edf0112697.png)

**Comment by unused** [comment]
That looks good, can you now test the script below but replace `YOUR_API_KEY` with your actual eyeson API key?

```
curl -X POST \
  -H "Authorization: YOUR_API_KEY" \
  -d "user[name]=Bob" \
  "https://api.eyeson.team/rooms"
```

You should receive either some JSON formatted details of the meeting you just started or a detailed error description.

**Comment by salmanaliawann** [comment]
Yes, I did received some JSON code in my Command Line Interface. I am reluctant to share the output as it contains confidential information. But I need this to be integrated in my PHP Laravel application, can you please guide in such matter?

**Comment by unused** [comment]
Good that you received a proper response. No worries, I just wanted to get sure there is no network issue with your environment. Practically there is no difference between the `curl` call from command line and the snippet from PHP. Can you please double check that you set the api key properly inside your application. It has to be a single string parameter.

If that still does not work please provide the exact error message.

**Comment by salmanaliawann** [comment]
Okay thank you for your valuable time. I will let you know if the error persists.

**Comment by salmanaliawann** [comment]
I receive the following error while trying to send a request to the given URL.
![image](https://user-images.githubusercontent.com/46898881/146214906-e2a2597d-0755-4c16-9100-536738d7a056.png)

**Comment by unused** [comment]
The certificate is valid, you'll have to check your machine to fix this error. The 404 response is right as you missed to set the endpoint to use `https://api.eyeson.team/rooms`. Please refer to [the documentation](https://eyeson-team.github.io/api/api-reference/#eyeson-room) for further details.

**Comment by salmanaliawann** [comment]
Hi there, 404 was fixed. Thank you for pointing out the obvious mistake. I am receiving 401 - Invalid API key response now. I have tried two API keys but the error persists. Can you guide me if there is something wrong with the code itself or the API key is problematic?

**Comment by unused** [comment]
Hi there, we're always happy to help. It is very likely that you do not pass a valid API key. This can have several reason like a secret is not passed properly, there is a mistake in you implementation, some additional characters like whitespaces are mixed into the credentials, etc. I'd suggest to use `curl` [on a cli](https://eyeson-team.github.io/api/getting-started/#start-and-join-eyeson-room) to check the key is correct. Afterwards try to debug your code to ensure the key given is the one you just checked. Let me know if you have still troubles with this.

**Comment by salmanaliawann** [comment]
It do work in the curl on my command interface but unfortunately not in my Laravel system as it returns 401. I have cross checked the API Key. Is there any issue that I should be looking for?

**Comment by salmanaliawann** [comment]
cURL

$post = [
            'name' => "Bob",
];
$header = [
            "content-type" => "application/json",
            "api-key" => "secret",
 ];

$ch = curl_init('https://api.eyeson.team/rooms');
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);

$response = curl_exec($ch);

curl_close($ch);

**Comment by salmanaliawann** [comment]
Laravel HTTP

$eyeson = Http::withHeaders([
            "content-type" => "application/json",
            "api-key" => "secret",
])->withOptions([
            "verify" => false,
 ])->post("https://api.eyeson.team/rooms", [
            'name' => "Bob",
 ]);

$statusCode = $eyeson->status();
$responseBody = json_decode($eyeson->getBody(), true);

**Comment by unused** [comment]
Your troubles seem not to be related with the eyeson API, please refer to the corresponding documentations of PHP or Laravel. However I've quickly corrected your plain PHP example above:

```php
<?php

$post = ['id' => 'demo', 'user' => ['name' => 'Bob']];
$header = ['Authorization: <your-api-key>'];

$ch = curl_init('https://api.eyeson.team/rooms');
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($post));
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);

$response = curl_exec($ch);

var_dump(curl_getinfo($ch, CURLINFO_HTTP_CODE));
var_dump(json_decode($response, true));

curl_close($ch);
```

**Comment by salmanaliawann** [comment]
Response below received from the provided snippet.

![image](https://user-images.githubusercontent.com/46898881/147916627-27c74be2-83c1-46a9-aa0c-4c762567661b.png)

**Comment by salmanaliawann** [comment]
But this still does not maps with your GitHub code as it establishes the connection. The real issue comes with the integration.

**Comment by unused** [comment]
Could you please be more specific? What do you mean by the integration? What problem does still exist? Thank you in advance.
