### ISSUE TITLE
Given the same link to two people find themselves in two different rooms

### ISSUE THREAD

**Issue by PaoloBoniccoBtB** [eyeson-team/eyeson-php#73]
Occasionally it happens that two people with the same eyeson call link do not see each other in call, as if they are in two different rooms.
What could be the problem that given the same link people do not see each other during the video call? On our side it turns out to be ok, can you give us a technical reason to investigate? Thank you very much

**Comment by unused** [comment]
As you [join participants](https://eyeson-team.github.io/api/api-reference/#eyeson-room) of the same meeting, ensure to use a unique identifier `id` and they are guaranteed to be in the same video conference.

> [...] given the same link [...]

I guess you're talking about the guest link that can be shared during an active meeting by the participants w/o further interaction with the eyeson API. Here as well you have to ensure the participants that share the guest-link are in the same meeting, the most straightforward way to do so is to use an unique identifier.

Let me know if you have any further questions!
