### ISSUE TITLE
eyeson video download

### ISSUE THREAD

**Issue by proshawkat** [eyeson-team/eyeson-php#74]
I want to download a specific video by recording id after the end of the call. I am getting 404 error. 

Start a recording:
 eyeson.send({ type: 'start_recording' }); 

end ot the call:  
    eyeson.send({
        type: 'stop_recording'
    });
response like this download null: 
{
  type: 'recording_update',
  recording: {
    id: '598d8812ac605e3e4892470b',
    created_at, // Timestamp
    duration, // in seconds
    links: {
      self: 'https://api.eyeson.team/recordings/598d8812ac605e3e4892470b',
      download: null
    },
    user: {
      id,
      name,
      avatar,
      guest,
    },
    room: {
      id,
      name,
      ready: true | false,
      shutdown: true | false,
      sip: { /* ... */ },
      guest_token
    }
  }
} 
Network call=    
![Untitled](https://user-images.githubusercontent.com/26435292/202151049-2f36b48b-a9f6-4f26-a69e-887d8f97e34f.png)

**Comment by unused** [comment]
The recording has to be post-processed and uploaded, and won't be available at the stop immediately. You can either listen to the websockets message  `recording_update` that provides a proper download link or setup [webhooks](https://eyeson-team.github.io/api/api-reference/#register-webhooks) for your API key. We recommend using webhooks as it is safer than to rely on a client, only requires a one-time setup, and also works if the meeting is shutdown w/o stopping the recording. Please do not hesitate to leave a comment if you have any further questions.
