### ISSUE TITLE
Embed room in an iframe

### ISSUE THREAD

**Issue by flodi** [eyeson-team/eyeson-php#8]
I'm implementing eyeson integration with the platform for a startup, and we would like to embed eyeson GUI inside an iframe.

At the moment - we are using PHP SDK - using the getURL() function I'm able to join rooms opening a new window, but if I embed that url in an iframe it does not work.

Do you have some snippets or example on how to do that?

Thank you

**Comment by unused** [comment]
When you want to use the web GUI inside of an iframe you have to ensure the element is allowed to request permissions for the media devices (camera and microphone) as well as allow fullscreen (on demand).

```html
<iframe src="<?php echo $room->getUrl() ?>"
             allowfullscreen
             allow="microphone https://app.eyeson.team; camera https://app.eyeson.team">
</iframe>
```
