### ISSUE TITLE
Embedding in Safari does not work

### ISSUE THREAD

**Issue by flodi** [eyeson-team/eyeson-php#9]
Hi, I'm embedding a video call through iframe just how you told me. It works just fine, except on Safari.

It seems Safari is confused by the fact that the auth request for microphone and camera cames from a different url from the main page one (my page).

Do you have any suggestions? Thank you

**Comment by unused** [comment]
We cannot detect any problems using Safari and an embedded web GUI for the eyeson service. Please check your application does ensure proper policies for a safe communication between your endpoints.
